{
  imports = [
    ./comment.nix
    ./comment-box.nix
    ./flash.nix
    ./grug-far.nix
    ./illuminate.nix
    ./markview.nix
    ./mini.nix
    ./persistence.nix
    ./snacks.nix
    ./spectre.nix
    ./todo-comments.nix
    ./ufo.nix
    ./undotree.nix
    ./whichkey.nix
    ./yanky.nix
  ];
}
