{
  imports = [
    ./keymaps.nix
    ./bufferline.nix
    ./dressing.nix
    ./lualine.nix
    ./noice.nix
    ./smart-splits.nix
    ./snacks.bufdelete.nix
    ./snacks.indent.nix
    ./snacks.dashboard.nix
    ./snacks.image.nix
    ./snacks.toggle.nix
    ./snacks.input.nix
    ./snacks.scroll.nix
    ./snacks.statuscolumn.nix
    ./mini.hipatterns.nix
    ./mini.icons.nix
  ];
}
